In [1]:
import tushare as ts
import pandas as pd
import numpy as np

In [2]:
db = ts.get_hist_data('600000',start = '2017-01-01',end = '2018-01-01')

In [3]:
db

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
date,,,,,,,,,,,,,,
2017-12-29,12.52,12.62,12.59,12.51,163518.27,0.05,0.40,12.598,12.642,12.757,214973.83,203101.34,295878.94,0.06
2017-12-28,12.60,12.66,12.54,12.53,238708.23,-0.08,-0.63,12.604,12.646,12.774,214424.05,202959.62,306991.75,0.08
2017-12-27,12.65,12.66,12.62,12.53,327318.81,-0.02,-0.16,12.636,12.661,12.792,208787.18,195230.47,315014.51,0.12
2017-12-26,12.57,12.66,12.64,12.56,152257.22,0.05,0.40,12.654,12.674,12.807,196603.11,181843.93,319571.96,0.05
2017-12-25,12.61,12.68,12.60,12.56,193066.62,-0.02,-0.16,12.676,12.685,12.823,202950.87,196988.30,328975.06,0.07
2017-12-22,12.68,12.72,12.62,12.61,160769.38,-0.08,-0.63,12.686,12.722,12.848,191228.84,214331.55,358946.86,0.06
2017-12-21,12.67,12.78,12.70,12.60,210523.88,-0.03,-0.24,12.688,12.752,12.871,191495.18,229550.83,380714.64,0.07
2017-12-20,12.76,12.76,12.71,12.60,266398.44,-0.04,-0.31,12.686,12.778,12.889,181673.76,243300.67,411144.74,0.09
2017-12-19,12.65,12.76,12.75,12.62,183996.03,0.10,0.79,12.694,12.803,12.915,167084.75,260225.76,455112.95,0.07
2017-12-18,12.71,12.71,12.65,12.61,134456.48,0.03,0.24,12.694,12.845,12.924,191025.74,365622.95,504002.86,0.05
2017-12-15,12.69,12.73,12.63,12.61,162101.08,-0.06,-0.47,12.758,12.872,12.934,237434.25,388656.54,528027.74,0.06
2017-12-14,12.79,12.79,12.69,12.66,161416.78,-0.05,-0.39,12.816,12.901,12.942,267606.48,411023.87,574590.96,0.06
2017-12-13,12.80,12.81,12.75,12.63,193453.38,0.00,0.00,12.870,12.923,12.927,304927.58,434798.55,584360.50,0.07
2017-12-12,12.97,12.97,12.75,12.74,303700.97,-0.22,-1.70,12.912,12.940,12.919,353366.76,457300.00,588726.09,0.11
2017-12-11,12.92,13.04,12.97,12.85,366499.03,0.04,0.31,12.996,12.960,12.912,540220.17,460961.81,590418.51,0.13
2017-12-08,12.98,12.99,12.92,12.87,312962.22,-0.04,-0.31,12.986,12.973,12.904,539878.83,503562.18,611098.23,0.11
2017-12-07,12.95,13.03,12.96,12.91,348022.28,0.00,0.00,12.986,12.989,12.889,554441.27,531878.44,620412.80,0.12
2017-12-06,13.12,13.16,12.96,12.91,435649.31,-0.21,-1.59,12.976,13.000,12.869,564669.53,578988.81,611743.37,0.16
2017-12-05,12.92,13.27,13.17,12.91,1237968.00,0.25,1.94,12.968,13.027,12.850,561233.24,650000.15,608527.98,0.44
2017-12-04,12.87,12.94,12.92,12.84,364792.34,0.01,0.08,12.924,13.003,12.818,381703.45,642382.76,565968.25,0.13
2017-12-01,12.93,12.95,12.92,12.81,385774.44,0.01,0.08,12.960,12.996,12.796,467245.54,667398.94,557737.04,0.14
2017-11-30,12.91,12.95,12.91,12.80,399163.56,-0.03,-0.23,12.992,12.982,12.779,509315.61,738158.04,554872.40,0.14
2017-11-29,12.95,13.04,12.92,12.81,418467.84,-0.02,-0.15,13.024,12.930,12.760,593308.10,733922.44,559047.75,0.15
2017-11-28,13.03,13.07,12.95,12.92,340319.09,-0.15,-1.15,13.086,12.898,12.741,738767.05,720152.19,555808.71,0.12
2017-11-27,13.09,13.12,13.10,12.81,792502.75,0.01,0.08,13.082,12.863,12.724,903062.06,719875.21,548853.12,0.28
2017-11-24,13.11,13.18,13.08,12.93,596124.81,0.02,0.15,13.032,12.834,12.704,867552.35,718634.27,546584.79,0.21
2017-11-23,13.24,13.32,13.07,12.91,819126.00,-0.16,-1.21,12.972,12.789,12.692,967000.46,708947.15,533115.46,0.29
2017-11-22,13.00,13.44,13.23,13.00,1145762.62,0.29,2.24,12.836,12.737,12.680,874536.79,644497.92,504796.74,0.41
2017-11-21,12.81,13.17,12.93,12.75,1161794.12,0.08,0.62,12.710,12.672,12.663,701537.32,567055.81,457880.52,0.41
2017-11-20,12.70,12.86,12.85,12.61,614954.19,0.07,0.55,12.644,12.633,12.660,536688.36,489553.73,413408.84,0.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-02-20,16.62,16.98,16.91,16.62,299499.84,0.27,1.62,16.784,16.761,16.681,197633.45,170186.04,145904.33,0.15
2017-02-17,16.78,16.82,16.64,16.59,138636.42,-0.14,-0.83,16.772,16.736,16.663,177719.22,153691.91,157581.70,0.07
2017-02-16,16.88,16.91,16.78,16.76,163278.31,-0.06,-0.36,16.800,16.735,16.645,177962.46,148002.56,160166.95,0.08
2017-02-15,16.82,16.93,16.84,16.75,256880.31,0.09,0.54,16.788,16.731,16.612,168092.87,140277.63,156151.11,0.13
2017-02-14,16.87,16.88,16.75,16.74,129872.35,-0.10,-0.59,16.754,16.716,16.578,139194.54,125874.47,147903.76,0.06
2017-02-13,16.88,16.90,16.85,16.78,199928.72,0.07,0.42,16.738,16.710,16.550,142738.64,127872.47,145408.52,0.10
2017-02-10,16.76,16.84,16.78,16.70,139852.62,0.06,0.36,16.700,16.682,16.517,129664.59,122496.14,142866.45,0.07
2017-02-09,16.68,16.77,16.72,16.59,113930.34,0.05,0.30,16.670,16.664,16.487,118042.65,122799.15,144471.62,0.06
2017-02-08,16.63,16.69,16.67,16.54,112388.67,0.00,0.00,16.674,16.646,16.466,112462.39,123586.80,151993.93,0.05
2017-02-07,16.65,16.74,16.67,16.63,147592.84,0.01,0.06,16.678,16.627,16.449,112554.40,123826.60,161203.86,0.07
2017-02-06,16.75,16.78,16.66,16.66,134558.50,0.03,0.18,16.682,16.600,16.431,113006.31,121622.61,161942.78,0.07
2017-02-03,16.82,16.85,16.63,16.62,81742.89,-0.11,-0.66,16.664,16.590,16.408,115327.69,161471.48,161345.94,0.04
2017-01-26,16.69,16.84,16.74,16.61,86029.07,0.05,0.30,16.658,16.554,16.380,127555.65,172331.34,163184.45,0.04
2017-01-25,16.69,16.74,16.69,16.61,112848.69,0.00,0.00,16.618,16.492,16.348,134711.21,172024.58,166103.76,0.05
2017-01-24,16.58,16.70,16.69,16.58,149852.41,0.12,0.72,16.576,16.439,16.320,135098.80,169933.04,165794.24,0.07
2017-01-23,16.66,16.69,16.57,16.51,146165.41,-0.03,-0.18,16.518,16.389,16.298,130238.90,162944.56,165542.85,0.07
2017-01-20,16.58,16.66,16.60,16.50,142882.69,0.06,0.36,16.516,16.352,16.279,207615.27,163236.76,163828.53,0.07
2017-01-19,16.43,16.64,16.54,16.43,121806.87,0.06,0.36,16.450,16.310,16.259,217107.02,166144.09,162433.99,0.06
2017-01-18,16.42,16.55,16.48,16.36,114786.63,0.08,0.49,16.366,16.286,16.248,209337.95,180401.05,162663.05,0.06
2017-01-17,16.46,16.54,16.40,16.37,125552.92,-0.16,-0.97,16.302,16.271,16.238,204767.29,198581.12,168186.63,0.06
2017-01-16,16.23,16.60,16.56,16.10,533047.25,0.29,1.78,16.260,16.261,16.244,195650.21,202262.96,166150.73,0.26
2017-01-13,16.10,16.29,16.27,16.10,190341.44,0.15,0.93,16.188,16.226,16.249,118858.25,161220.40,146764.05,0.09
2017-01-12,16.18,16.20,16.12,16.11,82961.50,-0.04,-0.25,16.170,16.206,16.270,115181.16,154037.56,152651.78,0.04
2017-01-11,16.24,16.24,16.16,16.15,91933.32,-0.03,-0.18,16.206,16.203,16.323,151464.16,160182.94,157433.98,0.04
2017-01-10,16.18,16.24,16.19,16.14,79967.56,-0.01,-0.06,16.240,16.201,16.374,192394.96,161655.43,160638.75,0.04
2017-01-09,16.24,16.29,16.20,16.13,149087.45,0.02,0.12,16.262,16.207,16.439,208875.70,168141.13,180820.15,0.07
2017-01-06,16.30,16.30,16.18,16.13,171955.98,-0.12,-0.74,16.264,16.206,16.496,203582.54,164420.29,187783.60,0.08
2017-01-05,16.30,16.38,16.30,16.24,264376.47,-0.03,-0.18,16.242,16.207,16.544,192893.96,158723.88,185803.09,0.13
2017-01-04,16.29,16.35,16.33,16.18,296587.34,0.03,0.18,16.200,16.209,16.582,168901.72,144925.05,180359.64,0.14
2017-01-03,16.21,16.44,16.30,16.17,162371.25,0.09,0.56,16.162,16.204,16.626,130915.90,137792.13,176004.31,0.08

In [4]:
#test
import myfun

In [5]:
thelong,theshort = myfun.get_CE(high=db.high,low=db.low,close=db.close,index=db.index)

In [6]:
thelong

date
2017-12-29    12.910
2017-12-28    12.880
2017-12-27    12.862
2017-12-26    12.838
2017-12-25    12.844
2017-12-22    12.888
2017-12-21    13.038
2017-12-20    13.026
2017-12-19    12.978
2017-12-18    12.906
2017-12-15    12.906
2017-12-14    12.912
2017-12-13    12.870
2017-12-12    12.792
2017-12-11    12.720
2017-12-08    12.708
2017-12-07    12.690
2017-12-06    12.702
2017-12-05    12.828
2017-12-04    12.852
2017-12-01    12.774
2017-11-30    12.618
2017-11-29    12.492
2017-11-28    12.276
2017-11-27    12.270
2017-11-24    12.180
2017-11-23    12.180
2017-11-22    12.312
2017-11-21    12.234
2017-11-20    12.218
               ...
2017-02-21    16.330
2017-02-20    16.374
2017-02-17    16.444
2017-02-16    16.450
2017-02-15    16.468
2017-02-14    16.468
2017-02-13    16.468
2017-02-10    16.364
2017-02-09    16.334
2017-02-08    16.334
2017-02-07    16.340
2017-02-06    16.304
2017-02-03    16.346
2017-01-26    16.348
2017-01-25    16.224
2017-01-24    16.154
2017-01-23    15.952
2017-01-20    15.820
2017-01-19    15.824
2017-01-18    15.844
2017-01-17    15.886
2017-01-16    16.090
2017-01-13    16.026
2017-01-12    16.026
2017-01-11    15.978
2017-01-10    15.876
2017-01-09    15.855
2017-01-06    15.830
2017-01-05    15.780
2017-01-04    15.630
Length: 243, dtype: float64

In [20]:
def get_atr(high,low,close,index):
    true_amplitude = []
    atr = []
    for i in range(len(index)-1):
        c1=(high[i+1] - low[i+1])
        c2=(abs(close[i+1] - high[i]))
        c3=(abs(close[i+1] - low[i]))
        true_amplitude.append(max(c1,c2,c3))
    for i in range(len(true_amplitude)):
        if  i < len(true_amplitude)-5:
            atr.append(sum(true_amplitude[i:i+5])/5)
        else:
            atr.append(sum(true_amplitude[i:])/len(true_amplitude[i:]))
    atr = pd.Series(atr,index=index[:-1])
    return atr

In [21]:
t_atr = get_atr(high=db.high,low=db.low,close=db.close,index=db.index)

In [22]:
t_atr

date
2017-12-29    0.120000
2017-12-28    0.130000
2017-12-27    0.136000
2017-12-26    0.144000
2017-12-25    0.142000
2017-12-22    0.144000
2017-12-21    0.134000
2017-12-20    0.138000
2017-12-19    0.154000
2017-12-18    0.178000
2017-12-15    0.178000
2017-12-14    0.176000
2017-12-13    0.190000
2017-12-12    0.216000
2017-12-11    0.240000
2017-12-08    0.244000
2017-12-07    0.250000
2017-12-06    0.246000
2017-12-05    0.204000
2017-12-04    0.196000
2017-12-01    0.222000
2017-11-30    0.274000
2017-11-29    0.316000
2017-11-28    0.388000
2017-11-27    0.390000
2017-11-24    0.420000
2017-11-23    0.420000
2017-11-22    0.376000
2017-11-21    0.312000
2017-11-20    0.294000
                ...
2017-02-21    0.250000
2017-02-20    0.202000
2017-02-17    0.162000
2017-02-16    0.160000
2017-02-15    0.154000
2017-02-14    0.144000
2017-02-13    0.144000
2017-02-10    0.162000
2017-02-09    0.172000
2017-02-08    0.172000
2017-02-07    0.170000
2017-02-06    0.182000
2017-02-03    0.168000
2017-01-26    0.164000
2017-01-25    0.172000
2017-01-24    0.182000
2017-01-23    0.246000
2017-01-20    0.280000
2017-01-19    0.272000
2017-01-18    0.252000
2017-01-17    0.238000
2017-01-16    0.170000
2017-01-13    0.138000
2017-01-12    0.138000
2017-01-11    0.154000
2017-01-10    0.188000
2017-01-09    0.195000
2017-01-06    0.203333
2017-01-05    0.220000
2017-01-04    0.270000
Length: 243, dtype: float64

In [6]:
len(atr)

243

In [7]:
len(true_amplitude)

243

In [8]:
len(db.index)

244

In [28]:
def get_CE(high,low,close,index):
    atr = get_atr(high,low,close,index)
    CE_long = []    #Chandelier Exit (long)
    CE_short = []   #Chandelier Exit (short)
    for i in range(len(atr)):
        if i < len(atr)-22:
            CE_long.append(max(high[i:i+22]) - atr[i]*3)
            CE_short.append(min(low[i:i+22]) + atr[i]*3)
        else:
            CE_long.append(max(high[i:]) - atr[i]*3)
            CE_short.append(min(low[i:]) + atr[i]*3)
    CE_long = pd.Series(CE_long,index=atr.index)
    CE_short = pd.Series(CE_short,index=atr.index)
    return CE_long,CE_short

In [29]:
tlong,tshort = get_CE(high=db.high,low=db.low,close=db.close,index=db.index)

In [31]:
tshort

date
2017-12-29    12.870
2017-12-28    12.920
2017-12-27    12.938
2017-12-26    12.992
2017-12-25    12.986
2017-12-22    13.032
2017-12-21    13.002
2017-12-20    13.014
2017-12-19    13.072
2017-12-18    12.914
2017-12-15    12.914
2017-12-14    12.908
2017-12-13    12.950
2017-12-12    13.028
2017-12-11    13.100
2017-12-08    13.112
2017-12-07    13.130
2017-12-06    13.118
2017-12-05    12.992
2017-12-04    12.968
2017-12-01    13.046
2017-11-30    13.202
2017-11-29    13.328
2017-11-28    13.544
2017-11-27    13.550
2017-11-24    13.640
2017-11-23    13.640
2017-11-22    13.508
2017-11-21    13.316
2017-11-20    13.262
               ...
2017-02-21    16.850
2017-02-20    16.706
2017-02-17    16.586
2017-02-16    16.580
2017-02-15    16.562
2017-02-14    16.532
2017-02-13    16.532
2017-02-10    16.586
2017-02-09    16.616
2017-02-08    16.616
2017-02-07    16.610
2017-02-06    16.646
2017-02-03    16.604
2017-01-26    16.592
2017-01-25    16.616
2017-01-24    16.646
2017-01-23    16.838
2017-01-20    16.940
2017-01-19    16.916
2017-01-18    16.856
2017-01-17    16.814
2017-01-16    16.610
2017-01-13    16.514
2017-01-12    16.524
2017-01-11    16.592
2017-01-10    16.694
2017-01-09    16.715
2017-01-06    16.740
2017-01-05    16.830
2017-01-04    16.980
Length: 243, dtype: float64