In [1]:
import tushare as ts
import numpy as np
import pandas as pd
import pymysql

In [2]:
con = pymysql.connect('localhost','airloki','lsz1365978','a_stocks')

2018.3.26:
    Q1：如果沪深300成分股更新了，数据库中会残留被移出成分股的股票的table
    Q2：数据输入失败，会留下一个空table

In [3]:
import MYDB

In [6]:
MYDB.update_hs300(con)

http://www.csindex.com.cn/uploads/file/autofile/closeweight/000300closeweight.xls
Update Stock 600000
Update Stock 600008
Update Stock 600009
Update Stock 600010
Update Stock 600011
Update Stock 600015
Update Stock 600016
Update Stock 600018
Update Stock 600019
Update Stock 600021
Update Stock 600023
Update Stock 600028
Update Stock 600029
Update Stock 600030
Update Stock 600031
Update Stock 600036
Update Stock 600038
Update Stock 600048
Update Stock 600050
Update Stock 600061
Update Stock 600066
Update Stock 600068
Update Stock 600074
Update Stock 600085
Update Stock 600089
Update Stock 600100
Update Stock 600104
Update Stock 600109
Update Stock 600111
Update Stock 600115
Update Stock 600118
Update Stock 600153
Update Stock 600157
Update Stock 600170
Update Stock 600177
Update Stock 600188
Update Stock 600196
Update Stock 600208
Update Stock 600219
Update Stock 600221
Update Stock 600233
Update Stock 600271
Update Stock 600276
Update Stock 600297
Update Stock 600309
Update Stock 600332
Update Stock 600340
Update Stock 600352
Update Stock 600362
Update Stock 600369
Update Stock 600372
Update Stock 600373
Update Stock 600376
Update Stock 600383
Update Stock 600390
Update Stock 600406
Update Stock 600415
Update Stock 600436
Update Stock 600482
Update Stock 600485
Update Stock 600489
Update Stock 600498
Update Stock 600518
Update Stock 600519
Update Stock 600522
Update Stock 600535
Update Stock 600547
Update Stock 600549
Update Stock 600570
Update Stock 600583
Update Stock 600585
Update Stock 600588
Update Stock 600606
Update Stock 600637
Update Stock 600649
Update Stock 600660
Update Stock 600663
Update Stock 600674
Update Stock 600682
Update Stock 600685
Update Stock 600688
Update Stock 600690
Update Stock 600703
Update Stock 600704
Update Stock 600705
Update Stock 600739
Update Stock 600741
Update Stock 600795
Update Stock 600804
Update Stock 600816
Update Stock 600820
Update Stock 600827
Update Stock 600837
Update Stock 600871
Update Stock 600886
Update Stock 600887
Update Stock 600893
Update Stock 600895
Update Stock 600900
Update Stock 600909
Update Stock 600919
Update Stock 600926
Update Stock 600958
Update Stock 600959
Update Stock 600977
Update Stock 600999
Update Stock 601006
Update Stock 601009
Update Stock 601012
Update Stock 601018
Update Stock 601021
Update Stock 601088
Update Stock 601099
Update Stock 601111
Update Stock 601117
Update Stock 601118
Update Stock 601155
Update Stock 601163
Update Stock 601166
Update Stock 601169
Update Stock 601186
Update Stock 601198
Update Stock 601211
Update Stock 601212
Update Stock 601216
Update Stock 601225
Update Stock 601228
Update Stock 601229
Update Stock 601288
Update Stock 601318
Update Stock 601328
Update Stock 601333
Update Stock 601336
Update Stock 601375
Update Stock 601377
Update Stock 601390
Update Stock 601398
Update Stock 601555
Update Stock 601600
Update Stock 601601
Update Stock 601607
Update Stock 601608
Update Stock 601611
Update Stock 601618
Update Stock 601628
Update Stock 601633
Update Stock 601668
Update Stock 601669
Update Stock 601688
Update Stock 601718
Update Stock 601727
Update Stock 601766
Update Stock 601788
Update Stock 601800
Update Stock 601818
Update Stock 601857
Update Stock 601866
Update Stock 601872
Update Stock 601877
Update Stock 601878
Update Stock 601881
Update Stock 601888
Update Stock 601898
Update Stock 601899
Update Stock 601901
Update Stock 601919
Update Stock 601933
Update Stock 601939
Update Stock 601958
Update Stock 601966
Can not get the data of601966
Update Stock 601985
Can not get the data of601985
Update Stock 601988
Can not get the data of601988
Update Stock 601989
Can not get the data of601989
Update Stock 601991
Can not get the data of601991
Update Stock 601992
Can not get the data of601992
Update Stock 601997
Can not get the data of601997
Update Stock 601998
Can not get the data of601998
Update Stock 603160
Can not get the data of603160
Update Stock 603799
Can not get the data of603799
Update Stock 603833
Can not get the data of603833
Update Stock 603858
Can not get the data of603858
Update Stock 603993
Can not get the data of603993
Update Stock 000001
Update Stock 000002
Update Stock 000008
Update Stock 000060
Update Stock 000063
Update Stock 000069
Update Stock 000100
Update Stock 000157
Update Stock 000166
Update Stock 000333
Update Stock 000338
Update Stock 000402
Update Stock 000413
Update Stock 000415
Update Stock 000423
Update Stock 000425
Update Stock 000503
Update Stock 000538
Update Stock 000540
Update Stock 000559
Update Stock 000568
Update Stock 000623
Update Stock 000625
Update Stock 000627
Update Stock 000630
Update Stock 000651
Update Stock 000671
Update Stock 000686
Update Stock 000709
Update Stock 000723
Update Stock 000725
Update Stock 000728
Update Stock 000738
Update Stock 000750
Update Stock 000768
Update Stock 000776
Update Stock 000783
Update Stock 000792
Update Stock 000826
Update Stock 000839
Update Stock 000858
Update Stock 000876
Update Stock 000895
Update Stock 000898
Update Stock 000938
Update Stock 000959
Update Stock 000961
Update Stock 000963
Update Stock 000983
Update Stock 001979
Update Stock 002007
Update Stock 002008
Update Stock 002024
Update Stock 002027
Update Stock 002044
Update Stock 002065
Update Stock 002074
Update Stock 002081
Update Stock 002142
Update Stock 002146
Update Stock 002153
Update Stock 002174
Update Stock 002202
Update Stock 002230
Update Stock 002236
Update Stock 002241
Update Stock 002252
Update Stock 002292
Update Stock 002294
Update Stock 002304
Update Stock 002310
Update Stock 002352
Update Stock 002385
Update Stock 002411
Update Stock 002415
Update Stock 002424
Update Stock 002426
Update Stock 002450
Update Stock 002456
Update Stock 002460
Update Stock 002465
Update Stock 002466
Update Stock 002468
Update Stock 002470
Update Stock 002475
Update Stock 002500
Update Stock 002508
Update Stock 002555
Update Stock 002558
Update Stock 002572
Update Stock 002594
Update Stock 002601
Update Stock 002602
Update Stock 002608
Update Stock 002624
Update Stock 002673
Update Stock 002714
Update Stock 002736
Update Stock 002739
Update Stock 002797
Update Stock 002831
Update Stock 002839
Update Stock 002841
Update Stock 300003
Update Stock 300015
Update Stock 300017
Update Stock 300024
Update Stock 300027
Update Stock 300033
Update Stock 300059
Update Stock 300070
Update Stock 300072
Update Stock 300122
Update Stock 300124
Update Stock 300136
Update Stock 300144
Update Stock 300251
Update Stock 300315

In [4]:
df = MYDB.df_of_stock(con,'600030')
df

             open   high  close    low       volume
0
2018-03-23  18.08  18.41  17.68  17.49  2.10434e+06
2018-03-22   18.7  19.13  18.78  18.57   1.5091e+06
2018-03-21   18.7  19.12  18.49  18.45  1.50352e+06
2018-03-20  18.33  18.76  18.67  18.24       916880
2018-03-19  18.38  18.71  18.54   18.2       939978
2018-03-16  18.77  18.94  18.35   18.3  1.03998e+06
2018-03-15   18.6  18.89  18.81  18.56       777289
2018-03-14  18.79  19.01   18.7  18.64       885780
2018-03-13   19.2  19.22  18.97  18.89  1.09697e+06
2018-03-12  19.05  19.43  19.29   18.9  1.91371e+06
2018-03-09  18.45  18.95  18.87  18.34   1.6736e+06
2018-03-08   18.3  18.41  18.39  18.16       797844
2018-03-07   18.3  18.66  18.28   18.2  1.27517e+06
2018-03-06  18.03  18.47  18.42  17.88  1.77203e+06
2018-03-05  17.83  18.07  17.88  17.81       694798
2018-03-02   17.9  18.13  17.84  17.81       899891
2018-03-01  17.89  18.25  18.14   17.8  1.11579e+06
2018-02-28  18.05  18.36   18.1  17.79  1.58573e+06
2018-02-27   18.6  18.61  18.25  18.14  1.55042e+06
2018-02-26   18.4  18.88  18.66  18.01  2.11992e+06
2018-02-23   18.1  18.45  18.19  17.93  1.58505e+06
2018-02-22  17.99  18.12  18.02  17.75  1.56017e+06
2018-02-14   17.6  17.67  17.63  17.33  1.03688e+06
2018-02-13  17.51  18.04  17.64  17.47  2.03542e+06
2018-02-12  17.42  17.55  17.33  17.12   1.6197e+06
2018-02-09  18.58  18.74  17.34  17.32  3.47827e+06
2018-02-08  19.48  19.75  19.26  19.06  1.84744e+06
2018-02-07  20.97  21.02  19.55  19.51  2.67964e+06
2018-02-06  21.24  21.62  20.54  20.38  3.36473e+06
2018-02-05  21.01  21.86  21.79  20.96  2.20892e+06
2018-02-02  21.18  21.63  21.53  20.81  2.01001e+06
2018-02-01   21.4  21.56  21.53  21.01  2.78675e+06
2018-01-31  21.45   21.7  21.31  20.94  2.47253e+06
2018-01-30  21.91  22.34  21.65  21.53  2.45154e+06
2018-01-29  22.47  22.73  22.12  22.01  2.64481e+06
2018-01-26  22.33  22.74  22.35  22.21  2.51998e+06
2018-01-25   22.5  22.85  22.34  22.24  3.17332e+06
2018-01-24   21.4  22.95  22.93  21.15  5.07089e+06
2018-01-23  21.37  21.86  21.28   20.9  3.35664e+06
2018-01-22   21.1  21.44  21.22  20.94     1.81e+06
2018-01-19  21.36  21.85  21.29  20.92  3.63018e+06
2018-01-18  21.15  21.64  21.42   20.9  2.95669e+06
2018-01-17   20.5  21.89  20.95   20.5  4.97888e+06
2018-01-16  19.26  20.37  20.26  19.19  2.33073e+06
2018-01-15  19.25  19.69  19.44  18.98  2.24135e+06
2018-01-12  19.25  19.58  19.33  19.12  1.04604e+06
2018-01-11  19.46  19.55  19.28  19.12   1.1338e+06
2018-01-10  19.47  19.74  19.61  19.23  1.50258e+06
2018-01-09  19.55  19.87  19.45  19.28  1.43919e+06
2018-01-08     19   19.8  19.57  18.91  2.48971e+06
2018-01-05  18.68  19.09  18.88  18.59  1.72885e+06
2018-01-04  18.64  18.84  18.68  18.47  1.14791e+06
2018-01-03  18.36  18.85  18.63  18.35  1.51967e+06
2018-01-02  18.13  18.52  18.45  18.13  1.39328e+06

In [5]:
data99 = ts.get_hist_data('600030',start = '2018-01-01')
data99

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
date,,,,,,,,,,,,,,
2018-03-23,18.08,18.41,17.68,17.49,2104342.00,-1.08,-5.76,18.432,18.628,18.456,1394764.28,1268754.42,1308637.23,2.14
2018-03-22,18.70,19.13,18.78,18.57,1509102.88,0.28,1.51,18.566,18.747,18.481,1181891.61,1225680.18,1282672.80,1.54
2018-03-21,18.70,19.12,18.49,18.45,1503518.50,-0.19,-1.02,18.572,18.708,18.443,1035528.91,1154554.26,1285225.91,1.53
2018-03-20,18.33,18.76,18.67,18.24,916879.75,0.13,0.70,18.614,18.687,18.400,911981.16,1131719.82,1261893.84,0.93
2018-03-19,18.38,18.71,18.54,18.20,939978.25,0.20,1.09,18.674,18.662,18.349,947998.46,1217235.07,1317820.78,0.96
2018-03-16,18.77,18.94,18.35,18.30,1039978.69,-0.45,-2.39,18.824,18.596,18.288,1142744.56,1192717.05,1351806.68,1.06
2018-03-15,18.60,18.89,18.81,18.56,777289.38,0.11,0.59,18.928,18.545,18.238,1269468.75,1178708.31,1473721.31,0.79
2018-03-14,18.79,19.01,18.70,18.64,885779.75,-0.25,-1.32,18.844,18.478,18.260,1273579.60,1212558.47,1527228.88,0.90
2018-03-13,19.20,19.22,18.97,18.89,1096966.25,-0.33,-1.71,18.760,18.418,18.303,1351458.47,1282553.30,1616921.71,1.12
2018-03-12,19.05,19.43,19.29,18.90,1913708.75,0.43,2.28,18.650,18.346,18.381,1486471.67,1327898.89,1730309.78,1.95
2018-03-09,18.45,18.95,18.87,18.34,1673599.62,0.48,2.61,18.368,18.283,18.506,1242689.53,1348520.04,1745070.33,1.71
2018-03-08,18.30,18.41,18.39,18.16,797843.62,0.12,0.66,18.162,18.215,18.639,1087947.86,1339665.42,1761890.86,0.81
2018-03-07,18.30,18.66,18.28,18.20,1275174.12,-0.14,-0.76,18.112,18.178,18.796,1151537.34,1415897.57,1861336.22,1.30
2018-03-06,18.03,18.47,18.42,17.88,1772032.25,0.55,3.08,18.076,18.113,18.948,1213648.14,1392067.87,1921204.22,1.81
2018-03-05,17.83,18.07,17.88,17.81,694798.06,0.05,0.28,18.042,18.035,19.109,1169326.11,1418406.49,1955179.60,0.71
2018-03-02,17.90,18.13,17.84,17.81,899891.25,-0.29,-1.60,18.198,17.980,19.321,1454350.55,1510896.31,2052680.12,0.92
2018-03-01,17.89,18.25,18.14,17.80,1115791.00,0.03,0.17,18.268,17.930,19.547,1591382.97,1768734.31,2133684.31,1.14
2018-02-28,18.05,18.36,18.10,17.79,1585728.12,-0.15,-0.82,18.244,18.042,19.757,1680257.80,1841899.29,2236560.61,1.62
2018-02-27,18.60,18.61,18.25,18.14,1550422.12,-0.40,-2.15,18.150,18.187,19.998,1570487.60,1951290.12,2410818.51,1.58
2018-02-26,18.40,18.88,18.66,18.01,2119920.25,0.47,2.58,18.028,18.416,20.150,1667486.87,2132720.66,2501129.65,2.16
2018-02-23,18.10,18.45,18.19,17.93,1585053.38,0.18,1.00,17.762,18.729,20.278,1567442.07,2141620.61,2485633.51,1.61
2018-02-22,17.99,18.12,18.02,17.75,1560165.12,0.39,2.21,17.592,19.063,20.433,1946085.65,2184116.31,2587889.68,1.59
2018-02-14,17.60,17.67,17.63,17.33,1036877.12,0.01,0.06,17.840,19.414,20.603,2003540.77,2306774.88,2657716.04,1.06
2018-02-13,17.51,18.04,17.64,17.47,2035418.50,0.31,1.79,18.224,19.782,20.769,2332092.65,2450340.56,2854816.03,2.07
2018-02-12,17.42,17.55,17.33,17.12,1619696.25,-0.02,-0.12,18.804,20.183,20.900,2597954.45,2491952.71,2869581.77,1.65
2018-02-09,18.58,18.74,17.34,17.32,3478271.25,-1.90,-9.88,19.696,20.662,21.005,2715799.15,2594463.94,2900664.67,3.54
2018-02-08,19.48,19.75,19.26,19.06,1847440.75,-0.29,-1.48,20.534,21.163,21.105,2422146.98,2498634.31,2779053.01,1.88
2018-02-07,20.97,21.02,19.55,19.51,2679636.50,-1.00,-4.87,20.988,21.471,21.106,2610008.98,2631221.94,2743370.74,2.73
2018-02-06,21.24,21.62,20.54,20.38,3364727.50,-1.25,-5.74,21.340,21.809,21.109,2568588.48,2870346.89,2684518.16,3.43
2018-02-05,21.01,21.86,21.79,20.96,2208919.75,0.27,1.25,21.562,21.883,21.054,2385950.98,2869538.64,2588241.48,2.25
2018-02-02,21.18,21.63,21.53,20.81,2010010.38,0.03,0.14,21.628,21.826,20.943,2473128.73,2829646.41,2602280.82,2.05
2018-02-01,21.40,21.56,21.53,21.01,2786750.75,0.24,1.13,21.792,21.802,20.811,2575121.65,2991663.05,2588222.73,2.84
2018-01-31,21.45,21.70,21.31,20.94,2472534.00,-0.32,-1.48,21.954,21.791,20.668,2652434.90,3008657.20,2506280.92,2.52
2018-01-30,21.91,22.34,21.65,21.53,2451540.00,-0.46,-2.08,22.278,21.755,20.534,3172105.30,3259291.50,2458637.67,2.50
2018-01-29,22.47,22.73,22.12,22.01,2644808.50,-0.22,-0.98,22.204,21.616,20.374,3353126.30,3247210.83,2405724.90,2.69
2018-01-26,22.33,22.74,22.35,22.21,2519975.00,0.02,0.09,22.024,21.348,20.172,3186164.10,3206865.40,2305660.55,2.57
2018-01-25,22.50,22.85,22.34,22.24,3173317.00,-0.58,-2.53,21.812,21.046,19.961,3408204.45,3059471.71,2230712.51,3.23
2018-01-24,21.40,22.95,22.93,21.15,5070886.00,1.72,8.11,21.628,20.740,19.749,3364879.50,2855519.54,2111319.89,5.17
2018-01-23,21.37,21.86,21.28,20.90,3356645.00,0.08,0.38,21.232,20.408,19.522,3346477.70,2498689.43,1907443.49,3.42
2018-01-22,21.10,21.44,21.22,20.94,1809997.50,-0.07,-0.33,21.028,20.225,19.362,3141295.35,2306944.32,1772711.91,1.84
2018-01-19,21.36,21.85,21.29,20.92,3630176.75,-0.12,-0.56,20.672,20.060,19.210,3227566.70,2374915.22,1708635.87,3.70
2018-01-18,21.15,21.64,21.42,20.90,2956692.25,0.48,2.29,20.280,19.819,19.055,2710738.96,2184782.41,1583974.94,3.01
2018-01-17,20.50,21.89,20.95,20.50,4978877.00,0.70,3.46,19.852,19.545,18.877,2346159.59,2003904.63,1479798.17,5.07
2018-01-16,19.26,20.37,20.26,19.19,2330733.25,0.81,4.17,19.584,19.313,18.743,1650901.16,1657983.83,1270818.68,2.37
2018-01-15,19.25,19.69,19.44,18.98,2241354.25,0.11,0.57,19.422,19.132,18.632,1472593.29,1564238.97,1183547.72,2.28
2018-01-12,19.25,19.58,19.33,19.12,1046038.06,0.05,0.26,19.448,18.995,18.557,1522263.74,1404455.70,1110348.32,1.07
2018-01-11,19.46,19.55,19.28,19.12,1133795.38,-0.33,-1.68,19.358,18.875,18.498,1658825.85,1401953.31,1096281.07,1.16
2018-01-10,19.47,19.74,19.61,19.23,1502584.88,0.17,0.87,19.238,18.757,18.455,1661649.68,1367120.23,1075201.78,1.53
2018-01-09,19.55,19.87,19.45,19.28,1439193.88,-0.09,-0.46,19.042,18.636,18.390,1665066.50,1316197.55,1042210.22,1.47
2018-01-08,19.00,19.80,19.57,18.91,2489706.50,0.69,3.65,18.842,18.498,18.355,1655884.65,1238479.50,1019637.24,2.54
2018-01-05,18.68,19.09,18.88,18.59,1728848.62,0.21,1.12,18.542,18.359,18.302,1286647.66,1042356.52,943502.89,1.76
2018-01-04,18.64,18.84,18.68,18.47,1147914.50,0.07,0.38,18.392,18.290,18.288,1145080.76,983167.47,921317.09,1.17
2018-01-03,18.36,18.85,18.63,18.35,1519669.00,0.19,1.03,18.276,18.208,18.318,1072590.78,955691.70,933805.67,1.55
2018-01-02,18.13,18.52,18.45,18.13,1393284.62,0.35,1.93,18.230,18.173,18.351,967328.61,883653.52,972996.87,1.42

In [39]:
def update_hs300(connect,start_D='2018-01-01',end_D=None):
    cursor = connect.cursor()
    hs300 = ts.get_hs300s().code
    for i in hs300:
        print('Update Stock '+i)
        sql01 = "drop table if exists s"+i
        sql02 = "create table s"+i+"""(date date,open float,high float,low float,close float,volume float)"""
        sql03 = "insert into s"+i+"(date,open,high,close,low,volume)values(%s,%s,%s,%s,%s,%s)"
        cursor.execute(sql01)
        cursor.execute(sql02)
        s_DB = ts.get_hist_data(i,start=start_D,end=end_D)
        if s_DB is None:
            print('Can not get the data of'+i)
            continue
        s_DB = s_DB.iloc[:,0:5]
        s_DB.insert(0,'date',s_DB.index)
        insert_data = np.array(s_DB)
        try:
            for row in insert_data:
                cursor.execute(sql03,list(row))
            connect.commit()
        except:
            connect.rollback()
            print('Fail to insert data of '+i+' into table')

In [17]:
con.rollback()

In [19]:
update_hs300(con)

http://www.csindex.com.cn/uploads/file/autofile/closeweight/000300closeweight.xls
Update Stock600000
Update Stock600008
Update Stock600009
Update Stock600010
Update Stock600011
Update Stock600015
Update Stock600016
Update Stock600018
Update Stock600019
Update Stock600021
Update Stock600023
Update Stock600028
Update Stock600029
Update Stock600030
Update Stock600031
Update Stock600036
Update Stock600038
Update Stock600048
Update Stock600050
Update Stock600061
Update Stock600066
Update Stock600068
Update Stock600074
Update Stock600085
Update Stock600089
Update Stock600100
Update Stock600104
Update Stock600109
Update Stock600111
Update Stock600115
Update Stock600118
Update Stock600153
Update Stock600157
Update Stock600170
Update Stock600177
Update Stock600188
Update Stock600196
Update Stock600208
Update Stock600219
Update Stock600221
Update Stock600233
Update Stock600271
Update Stock600276
Update Stock600297
Update Stock600309
Update Stock600332
Update Stock600340
Update Stock600352
Update Stock600362
Update Stock600369
Update Stock600372
Update Stock600373
Update Stock600376
Update Stock600383
Update Stock600390
Update Stock600406
Update Stock600415
Update Stock600436
Update Stock600482
Update Stock600485
Update Stock600489
Update Stock600498
Update Stock600518
Update Stock600519
Update Stock600522
Update Stock600535
Update Stock600547
Update Stock600549
Update Stock600570
Update Stock600583
Update Stock600585
Update Stock600588
Update Stock600606
Update Stock600637
Update Stock600649
Update Stock600660
Update Stock600663
Update Stock600674
Update Stock600682
Update Stock600685
Update Stock600688
Update Stock600690
Update Stock600703
Update Stock600704
Update Stock600705
Update Stock600739
Update Stock600741
Update Stock600795
Update Stock600804
Update Stock600816
Update Stock600820
Update Stock600827
Update Stock600837
Update Stock600871
Update Stock600886
Update Stock600887
Update Stock600893
Update Stock600895
Update Stock600900
Update Stock600909
Update Stock600919
Update Stock600926
Update Stock600958
Update Stock600959
Update Stock600977
Update Stock600999
Update Stock601006
Update Stock601009
Update Stock601012
Update Stock601018
Update Stock601021
Update Stock601088
Update Stock601099
Update Stock601111
Update Stock601117
Update Stock601118
Update Stock601155
Update Stock601163
Update Stock601166
Update Stock601169
Update Stock601186
Update Stock601198
Update Stock601211
Update Stock601212
Update Stock601216
Update Stock601225
Update Stock601228
Update Stock601229
Update Stock601288
Update Stock601318
Update Stock601328
Update Stock601333
Update Stock601336
Update Stock601375
Update Stock601377
Update Stock601390
Update Stock601398
Update Stock601555
Update Stock601600
Update Stock601601
Update Stock601607
Update Stock601608
Update Stock601611
Update Stock601618
Update Stock601628
Update Stock601633
Update Stock601668
Update Stock601669
Update Stock601688
Update Stock601718
Update Stock601727
Update Stock601766
Update Stock601788
Update Stock601800
Update Stock601818
Update Stock601857
Update Stock601866
Update Stock601872
Update Stock601877
Update Stock601878
Update Stock601881
Update Stock601888
Update Stock601898
Update Stock601899
Update Stock601901
Update Stock601919
Update Stock601933
Update Stock601939
Update Stock601958
Update Stock601966
Can not get the data of601966
Update Stock601985
Can not get the data of601985
Update Stock601988
Can not get the data of601988
Update Stock601989
Can not get the data of601989
Update Stock601991
Can not get the data of601991
Update Stock601992
Can not get the data of601992
Update Stock601997
Can not get the data of601997
Update Stock601998
Can not get the data of601998
Update Stock603160
Can not get the data of603160
Update Stock603799
Can not get the data of603799
Update Stock603833
Can not get the data of603833
Update Stock603858
Can not get the data of603858
Update Stock603993
Can not get the data of603993
Update Stock000001
Update Stock000002
Update Stock000008
Update Stock000060
Update Stock000063
Update Stock000069
Update Stock000100
Update Stock000157
Update Stock000166
Update Stock000333
Update Stock000338
Update Stock000402
Update Stock000413
Update Stock000415
Update Stock000423
Update Stock000425
Update Stock000503
Update Stock000538
Update Stock000540
Update Stock000559
Update Stock000568
Update Stock000623
Update Stock000625
Update Stock000627
Update Stock000630
Update Stock000651
Update Stock000671
Update Stock000686
Update Stock000709
Update Stock000723
Update Stock000725
Update Stock000728
Update Stock000738
Update Stock000750
Update Stock000768
Update Stock000776
Update Stock000783
Update Stock000792
Update Stock000826
Update Stock000839
Update Stock000858
Update Stock000876
Update Stock000895
Update Stock000898
Update Stock000938
Update Stock000959
Update Stock000961
Update Stock000963
Update Stock000983
Update Stock001979
Update Stock002007
Update Stock002008
Update Stock002024
Update Stock002027
Update Stock002044
Update Stock002065
Update Stock002074
Update Stock002081
Update Stock002142
Update Stock002146
Update Stock002153
Update Stock002174
Update Stock002202
Update Stock002230
Update Stock002236
Update Stock002241
Update Stock002252
Update Stock002292
Update Stock002294
Update Stock002304
Update Stock002310
Update Stock002352
Update Stock002385
Update Stock002411
Update Stock002415
Update Stock002424
Update Stock002426
Update Stock002450
Update Stock002456
Update Stock002460
Update Stock002465
Update Stock002466
Update Stock002468
Update Stock002470
Update Stock002475
Update Stock002500
Update Stock002508
Update Stock002555
Update Stock002558
Update Stock002572
Update Stock002594
Update Stock002601
Update Stock002602
Update Stock002608
Update Stock002624
Update Stock002673
Update Stock002714
Update Stock002736
Update Stock002739
Update Stock002797
Update Stock002831
Update Stock002839
Update Stock002841
Update Stock300003
Update Stock300015
Update Stock300017
Update Stock300024
Update Stock300027
Update Stock300033
Update Stock300059
Update Stock300070
Update Stock300072
Update Stock300122
Update Stock300124
Update Stock300136
Update Stock300144
Update Stock300251
Update Stock300315

In [40]:
def df_of_stock(connect,stock):
    sql04 = """select * from s"""+stock
    cursor = connect.cursor()
    cursor.execute(sql04)
    p_df = pd.DataFrame(np.array(cursor.fetchall()))
    df = p_df.iloc[:,1:]
    df.index = p_df[0]
    df.columns = ['open','high','close','low','volume']
    return df

In [41]:
t_df = df_of_stock(con,'002304')
t_df

              open    high   close     low   volume
0
2018-03-23     107  108.93  107.25   105.3  31721.6
2018-03-22  113.89  113.89  111.07   110.7  34325.7
2018-03-21  112.47  114.99   113.9   112.4  30702.2
2018-03-20  112.35   113.2   112.4  111.38  24804.7
2018-03-19  113.48  114.65  112.83   111.9  28220.9
2018-03-16   115.2   115.8  113.04     113  27359.7
2018-03-15     113  115.55   114.5     113  36974.3
2018-03-14  112.21  113.78   113.1   111.8  45153.8
2018-03-13  114.98  114.98   112.2     112  50621.8
2018-03-12  118.88  118.88  115.47   113.4  71876.2
2018-03-09  116.76  117.98  117.75  115.96    32882
2018-03-08   114.4  116.97  116.82   112.6  41298.8
2018-03-07  114.71  117.49   113.3   112.5  45863.6
2018-03-06  117.59  117.85     115  110.58  59132.7
2018-03-05   119.7  121.49  116.93     116  40051.2
2018-03-02     120  121.47   119.7  118.05  20393.2
2018-03-01     118  121.86  121.28   116.6  42581.8
2018-02-28     120  123.18  117.99     116   130020
2018-02-27     130     130  127.21  126.01  30546.4
2018-02-26     132     132  128.78   127.8  34635.2
2018-02-23   132.5  132.95   130.8  128.88  32803.4
2018-02-22  126.79   131.6   131.3  126.57  43494.2
2018-02-14  123.02  125.88   124.8     123  33352.2
2018-02-13  125.99  127.98   123.3  123.26  47325.3
2018-02-12  123.11  127.85  125.61  123.11  55317.7
2018-02-09   121.5   123.8  123.05   117.2  50026.6
2018-02-08   118.8   125.3  124.99     118  56317.9
2018-02-07  122.86  127.86  118.93     116    70909
2018-02-06     117  122.55  121.77     116    74414
2018-02-05  126.36  126.36  121.89  117.12  77021.1
2018-02-02   128.6  131.12  128.95  125.85  32220.2
2018-02-01  128.52  131.27  129.71  126.99  40656.3
2018-01-31   126.5  130.61  129.95   126.5  43666.1
2018-01-30  126.98  128.28  124.99  124.17  45768.1
2018-01-29  133.28   133.5  127.77  127.01  60272.8
2018-01-26  131.72  132.44  131.94  130.13  36718.2
2018-01-25  134.11   134.7  130.75  129.27  56545.4
2018-01-24   136.1  136.48  133.35  133.01  46129.8
2018-01-23  133.88     137  136.28  132.11  67902.2
2018-01-22     133   135.5   133.9   131.5  69089.5
2018-01-19  130.31  131.44  129.99   128.1  52231.6
2018-01-18  129.36  133.11  131.23  128.41  53316.3
2018-01-17  133.34  134.48  128.97  127.56  63628.1
2018-01-16  133.67   138.5   133.8  131.71  65864.8
2018-01-15   136.5  137.83  135.01  133.68  54578.6
2018-01-12     135  137.07  136.98   133.5  50338.2
2018-01-11  138.89     139   135.8  133.34  56287.1
2018-01-10  129.59  139.02   138.9  129.59  74872.7
2018-01-09  125.68  134.38  131.15  125.06  69485.1
2018-01-08   122.2  127.77  126.32   121.2  46252.1
2018-01-05   121.4   123.5  122.98  119.35  53654.1
2018-01-04  115.87  122.11     121  115.36  71915.9
2018-01-03  115.92  117.05  115.25  114.11  54049.9
2018-01-02   116.2  116.42     116  114.25  36006.7

In [42]:
data99 = ts.get_hist_data('002304',start = '2018-01-01')
data99

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
date,,,,,,,,,,,,,,
2018-03-23,107.00,108.93,107.25,105.30,31721.63,-3.82,-3.44,111.490,112.576,116.026,29955.01,38176.09,42958.30,0.26
2018-03-22,113.89,113.89,111.07,110.70,34325.69,-2.83,-2.48,112.648,113.626,117.204,29082.62,38292.12,43012.39,0.28
2018-03-21,112.47,114.99,113.90,112.40,30702.17,1.50,1.33,113.334,114.201,118.215,29612.35,38989.43,43470.81,0.25
2018-03-20,112.35,113.20,112.40,111.38,24804.68,-0.43,-0.38,113.174,114.141,118.760,32502.67,40505.58,43603.32,0.20
2018-03-19,113.48,114.65,112.83,111.90,28220.88,-0.21,-0.19,113.134,114.401,119.305,37666.10,43938.38,44729.35,0.23
2018-03-16,115.20,115.80,113.04,113.00,27359.67,-1.46,-1.27,113.662,114.811,119.944,46397.17,45121.41,46084.19,0.22
2018-03-15,113.00,115.55,114.50,113.00,36974.33,1.40,1.24,114.604,115.477,120.445,47501.63,44424.77,47217.54,0.30
2018-03-14,112.21,113.78,113.10,111.80,45153.79,0.90,0.80,115.068,116.155,120.969,48366.52,44985.51,48184.72,0.36
2018-03-13,114.98,114.98,112.20,112.00,50621.84,-3.27,-2.83,115.108,116.644,121.260,48508.49,53472.15,49472.48,0.41
2018-03-12,118.88,118.88,115.47,113.40,71876.20,-2.28,-1.94,115.668,118.145,121.739,50210.66,51464.61,50662.09,0.58
2018-03-09,116.76,117.98,117.75,115.96,32881.97,0.93,0.80,115.960,119.476,122.060,43845.66,47740.51,50919.33,0.27
2018-03-08,114.40,116.97,116.82,112.60,41298.79,3.52,3.11,116.350,120.781,122.620,41347.91,47732.65,50886.24,0.33
2018-03-07,114.71,117.49,113.30,112.50,45863.64,-1.70,-1.48,117.242,122.229,123.264,41604.50,47952.19,50854.12,0.37
2018-03-06,117.59,117.85,115.00,110.58,59132.72,-1.93,-1.65,118.180,123.379,124.097,58435.81,46701.05,50744.24,0.48
2018-03-05,119.70,121.49,116.93,116.00,40051.17,-2.77,-2.31,120.622,124.209,124.596,52718.56,45520.31,50076.00,0.32
2018-03-02,120.00,121.47,119.70,118.05,20393.21,-1.58,-1.30,122.992,125.077,125.138,51635.37,47046.97,51087.09,0.16
2018-03-01,118.00,121.86,121.28,116.60,42581.78,3.29,2.79,125.212,125.412,125.750,54117.40,50010.31,51903.33,0.34
2018-02-28,120.00,123.18,117.99,116.00,130020.18,-9.22,-7.25,127.216,125.783,126.224,54299.88,51383.93,52601.51,1.05
2018-02-27,130.00,130.00,127.21,126.01,30546.44,-1.57,-1.22,128.578,125.877,126.992,34966.30,45472.81,48406.99,0.25
2018-02-26,132.00,132.00,128.78,127.80,34635.22,-2.02,-1.54,127.796,125.333,127.446,38322.07,49859.56,50274.78,0.28
2018-02-23,132.50,132.95,130.80,128.88,32803.39,-0.50,-0.38,127.162,124.644,127.702,42458.57,54098.15,51997.50,0.26
2018-02-22,126.79,131.60,131.30,126.57,43494.18,6.50,5.21,125.612,124.459,127.661,45903.23,54039.83,52968.91,0.35
2018-02-14,123.02,125.88,124.80,123.00,33352.25,1.50,1.22,124.350,124.300,127.658,48467.97,53756.04,53460.01,0.27
2018-02-13,125.99,127.98,123.30,123.26,47325.31,-2.31,-1.84,123.176,124.815,127.866,55979.32,54787.42,54973.81,0.38
2018-02-12,123.11,127.85,125.61,123.11,55317.74,2.56,2.08,122.870,124.984,128.391,61397.05,54631.70,55900.78,0.45
2018-02-09,121.50,123.80,123.05,117.20,50026.65,-1.94,-1.55,122.126,125.200,128.861,65737.73,55127.20,55863.83,0.40
2018-02-08,118.80,125.30,124.99,118.00,56317.89,6.06,5.09,123.306,126.089,129.558,62176.43,53796.35,55879.41,0.45
2018-02-07,122.86,127.86,118.93,116.00,70908.99,-2.84,-2.33,124.250,126.665,130.098,59044.11,53819.10,55877.87,0.57
2018-02-06,117.00,122.55,121.77,116.00,74414.00,-0.12,-0.10,126.454,128.107,131.097,53595.53,51341.18,56076.05,0.60
2018-02-05,126.36,126.36,121.89,117.12,77021.10,-7.06,-5.47,127.098,129.558,131.566,47866.34,50690.00,55829.61,0.62
2018-02-02,128.60,131.12,128.95,125.85,32220.19,-0.76,-0.59,128.274,130.759,131.787,44516.67,49896.84,54291.16,0.26
2018-02-01,128.52,131.27,129.71,126.99,40656.29,-0.24,-0.18,128.872,130.863,131.489,45416.27,51897.98,55362.85,0.33
2018-01-31,126.50,130.61,129.95,126.50,43666.06,4.96,3.97,129.080,131.015,131.053,48594.09,53163.99,56925.84,0.35
2018-01-30,126.98,128.28,124.99,124.17,45768.05,-2.78,-2.18,129.760,130.917,130.318,49086.84,55160.19,57445.03,0.37
2018-01-29,133.28,133.50,127.77,127.01,60272.78,-4.17,-3.16,132.018,131.798,129.868,53513.67,57169.87,56956.96,0.49
2018-01-26,131.72,132.44,131.94,130.13,36718.16,1.19,0.91,133.244,132.522,129.230,55277.01,56600.45,56703.64,0.30
2018-01-25,134.11,134.70,130.75,129.27,56545.38,-2.60,-1.95,132.854,133.026,128.544,58379.70,57962.46,58534.51,0.46
2018-01-24,136.10,136.48,133.35,133.01,46129.82,-2.93,-2.15,132.950,133.531,127.666,57733.89,57936.63,57719.84,0.37
2018-01-23,133.88,137.00,136.28,132.11,67902.19,2.38,1.78,132.074,134.086,126.789,61233.55,60810.93,57225.75,0.55
2018-01-22,133.00,135.50,133.90,131.50,69089.52,3.91,3.01,131.578,133.573,125.922,60826.07,60969.22,55417.41,0.56
2018-01-19,130.31,131.44,129.99,128.10,52231.59,-1.24,-0.94,131.800,132.815,125.089,57923.89,58685.48,53472.13,0.42
2018-01-18,129.36,133.11,131.23,128.41,53316.32,2.26,1.75,133.198,132.114,124.545,57545.22,58827.72,53505.11,0.43
2018-01-17,133.34,134.48,128.97,127.56,63628.13,-4.83,-3.61,134.112,131.091,123.880,58139.38,60687.69,53786.39,0.51
2018-01-16,133.67,138.50,133.80,131.71,65864.79,-1.21,-0.90,136.098,129.719,123.133,60388.30,59729.86,52451.49,0.53
2018-01-15,136.50,137.83,135.01,133.68,54578.62,-1.97,-1.44,135.568,127.939,122.060,61112.37,56744.05,51164.99,0.44
2018-01-12,135.00,137.07,136.98,133.50,50338.25,1.18,0.87,133.830,125.938,120.915,59447.06,56806.83,50082.45,0.41
2018-01-11,138.89,139.00,135.80,133.34,56287.11,-3.10,-2.23,131.030,124.062,119.790,60110.23,59106.57,48825.90,0.45
2018-01-10,129.59,139.02,138.90,129.59,74872.73,7.75,5.91,128.070,121.801,118.755,63235.99,57503.05,48277.01,0.60
2018-01-09,125.68,134.38,131.15,125.06,69485.12,4.83,3.82,123.340,119.492,117.435,59071.42,53640.58,46580.35,0.56
2018-01-08,122.20,127.77,126.32,121.20,46252.11,3.34,2.72,120.310,118.270,116.427,52375.74,49865.60,45308.91,0.37
2018-01-05,121.40,123.50,122.98,119.35,53654.07,1.98,1.64,118.046,117.363,115.518,54166.60,48258.78,44254.31,0.43
2018-01-04,115.87,122.11,121.00,115.36,71915.93,5.75,4.99,117.094,116.975,114.694,58102.90,48182.49,42816.61,0.58
2018-01-03,115.92,117.05,115.25,114.11,54049.89,-0.75,-0.65,115.532,116.670,114.093,51770.11,46885.09,41239.84,0.44
2018-01-02,116.20,116.42,116.00,114.25,36006.70,1.00,0.87,115.644,116.546,113.798,48209.74,45173.11,41060.63,0.29

In [2]:
s_DB = ts.get_hist_data('600000',start = '2018-01-01',end = None)

In [4]:
myDB = pymysql.connect('localhost','airloki','lsz1365978','a_stocks')
cursor = myDB.cursor()

In [3]:
s_DB

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
date,,,,,,,,,,,,,,
2018-03-23,12.00,12.06,11.70,11.64,571063.94,-0.55,-4.49,12.172,12.294,12.401,283003.35,258682.27,297279.82,0.20
2018-03-22,12.35,12.35,12.26,12.25,229484.84,-0.03,-0.24,12.294,12.372,12.452,222353.36,225134.16,288094.88,0.08
2018-03-21,12.34,12.40,12.30,12.28,238784.66,-0.02,-0.16,12.318,12.393,12.470,211031.94,224349.81,297626.78,0.08
2018-03-20,12.28,12.39,12.30,12.25,206722.83,-0.01,-0.08,12.336,12.412,12.478,208884.21,239288.92,301986.45,0.07
2018-03-19,12.31,12.33,12.30,12.26,168960.48,0.00,0.00,12.374,12.431,12.488,217829.65,245839.31,319100.42,0.06
2018-03-16,12.36,12.40,12.31,12.30,267814.00,-0.08,-0.65,12.416,12.442,12.498,234361.19,258286.72,343051.99,0.10
2018-03-15,12.35,12.41,12.38,12.34,172877.73,-0.01,-0.08,12.450,12.452,12.522,227914.97,254529.45,404289.97,0.06
2018-03-14,12.45,12.45,12.39,12.38,228046.03,-0.10,-0.80,12.468,12.460,12.558,237667.68,271732.71,450359.52,0.08
2018-03-13,12.50,12.58,12.49,12.43,251450.00,-0.01,-0.08,12.488,12.466,12.611,269693.63,288817.05,539342.28,0.09
2018-03-12,12.53,12.54,12.51,12.46,251618.20,0.03,0.24,12.488,12.485,12.660,273848.97,312233.13,648949.28,0.09
2018-03-09,12.49,12.51,12.48,12.42,235582.88,0.01,0.08,12.468,12.507,12.709,282212.25,335877.37,711443.20,0.08
2018-03-08,12.55,12.55,12.47,12.40,221641.31,-0.02,-0.16,12.454,12.531,12.742,281143.94,351055.60,735562.44,0.08
2018-03-07,12.51,12.60,12.49,12.46,388175.75,0.00,0.00,12.452,12.546,12.784,305797.74,370903.75,811267.04,0.14
2018-03-06,12.48,12.51,12.49,12.38,272226.69,0.07,0.56,12.444,12.543,12.818,307940.46,364683.99,850709.88,0.10
2018-03-05,12.41,12.48,12.41,12.34,293434.62,0.00,0.00,12.482,12.545,12.848,350617.30,392361.53,891000.55,0.10
2018-03-02,12.40,12.46,12.41,12.36,230241.31,-0.06,-0.48,12.546,12.554,12.901,389542.49,427817.27,953220.37,0.08
2018-03-01,12.40,12.50,12.46,12.38,344910.31,0.00,0.00,12.608,12.591,12.952,420967.26,554050.49,1050918.15,0.12
2018-02-28,12.61,12.66,12.45,12.44,398889.38,-0.24,-1.89,12.640,12.655,13.012,436009.76,628986.33,1122167.44,0.14
2018-02-27,12.75,12.76,12.68,12.61,485610.88,-0.05,-0.39,12.642,12.755,13.069,421427.51,789867.51,1292049.79,0.17
2018-02-26,12.77,12.84,12.73,12.61,488060.56,0.01,0.08,12.608,12.835,13.080,434105.76,985665.42,1376682.97,0.17
2018-02-23,12.66,12.78,12.72,12.59,387365.16,0.09,0.71,12.562,12.910,13.083,466092.05,1087009.02,1488536.84,0.14
2018-02-22,12.60,12.68,12.62,12.53,420122.84,0.16,1.28,12.574,12.952,13.109,687133.72,1120069.29,1554993.02,0.15
2018-02-14,12.50,12.55,12.46,12.38,325978.12,-0.05,-0.40,12.670,13.021,13.140,821962.90,1251630.33,1589790.91,0.12
2018-02-13,12.55,12.68,12.51,12.50,549002.12,0.02,0.16,12.868,13.092,13.173,1158307.50,1336735.78,1637058.41,0.20
2018-02-12,12.66,12.68,12.50,12.43,647992.00,-0.28,-2.19,13.062,13.151,13.192,1537225.07,1389639.58,1647054.63,0.23
2018-02-09,12.89,12.98,12.78,12.24,1492573.50,-0.32,-2.44,13.258,13.247,13.218,1707926.00,1478623.48,1645315.37,0.53
2018-02-08,13.34,13.40,13.10,12.95,1094268.75,-0.35,-2.60,13.330,13.312,13.224,1553004.86,1547785.80,1582788.41,0.39
2018-02-07,13.58,13.90,13.45,13.24,2007701.12,-0.03,-0.22,13.372,13.368,13.216,1681297.76,1615348.55,1546983.18,0.71
2018-02-06,13.29,13.50,13.48,13.20,2443590.00,-0.01,-0.07,13.316,13.383,13.195,1515164.06,1794232.07,1491938.11,0.87
2018-02-05,13.00,13.54,13.48,12.98,1501496.62,0.34,2.59,13.240,13.325,13.156,1242054.08,1767700.52,1382866.33,0.53
2018-02-02,13.19,13.19,13.14,13.01,717967.81,-0.16,-1.20,13.236,13.255,13.116,1249320.96,1890064.66,1323486.44,0.26
2018-02-01,13.14,13.33,13.31,12.94,1735733.25,0.14,1.06,13.294,13.266,13.094,1542566.75,1989916.75,1303101.42,0.62
2018-01-31,13.05,13.19,13.17,12.98,1177032.62,0.06,0.46,13.364,13.259,13.061,1549399.35,1927951.50,1230256.66,0.42
2018-01-30,13.45,13.49,13.10,13.09,1078040.12,-0.36,-2.67,13.450,13.253,13.036,2073300.07,1937381.05,1190324.58,0.38
2018-01-29,13.48,13.53,13.46,13.32,1537831.00,0.05,0.37,13.410,13.233,13.018,2293346.95,1904469.69,1152084.10,0.55
2018-01-26,13.65,13.72,13.43,13.36,2184196.75,-0.22,-1.61,13.274,13.189,12.974,2530808.35,1812007.27,1083368.47,0.78
2018-01-25,13.54,13.76,13.66,13.36,1769896.25,0.09,0.66,13.238,13.136,12.930,2437266.75,1617791.01,986094.04,0.63
2018-01-24,12.97,14.00,13.60,12.89,3796536.25,0.70,5.43,13.154,13.064,12.878,2306503.65,1478617.80,913965.17,1.35
2018-01-23,12.75,12.92,12.90,12.68,2178274.50,0.13,1.02,13.056,13.006,12.830,1801462.02,1189644.16,731751.22,0.78
2018-01-22,12.93,13.15,12.78,12.71,2725138.00,-0.46,-3.47,13.056,12.987,12.815,1515592.42,998032.14,632490.82,0.97
2018-01-19,13.33,13.61,13.25,13.18,1716488.75,0.01,0.08,13.104,12.977,12.807,1093206.19,756908.23,504272.39,0.61
2018-01-18,13.14,13.25,13.24,13.05,1116080.75,0.14,1.07,13.034,12.921,12.779,798315.27,616286.10,428974.15,0.40
2018-01-17,12.91,13.42,13.11,12.89,1271328.12,0.21,1.63,12.974,12.863,12.753,650731.95,532561.83,386490.03,0.45
2018-01-16,12.97,13.06,12.90,12.78,748926.50,-0.12,-0.92,12.956,12.819,12.735,577826.30,443268.12,332123.43,0.27
2018-01-15,12.88,13.08,13.02,12.85,613206.81,0.11,0.85,12.918,12.802,12.722,480471.86,399698.52,301399.93,0.22
2018-01-12,12.97,13.00,12.90,12.90,242034.19,-0.04,-0.31,12.850,12.759,12.703,420610.28,354729.67,278844.64,0.09
2018-01-11,12.95,13.04,12.94,12.87,378164.12,-0.08,-0.61,12.808,12.723,12.692,434256.93,354397.07,274813.77,0.13
2018-01-10,12.70,13.09,13.02,12.68,906799.88,0.32,2.52,12.752,12.691,12.683,414391.71,349312.54,265578.23,0.32
2018-01-09,12.68,12.74,12.71,12.66,262154.31,0.03,0.24,12.682,12.653,12.669,308709.93,273858.27,235423.29,0.09
2018-01-08,12.69,12.71,12.68,12.63,313898.88,-0.01,-0.08,12.686,12.642,12.682,318925.18,266949.50,240640.52,0.11
2018-01-05,12.67,12.71,12.69,12.62,310267.44,0.03,0.24,12.668,12.636,12.694,288849.05,251636.55,240593.69,0.11
2018-01-04,12.70,12.73,12.66,12.62,278838.03,0.00,0.00,12.638,12.637,12.708,274537.21,241662.20,242481.43,0.10
2018-01-03,12.73,12.80,12.67,12.66,378391.00,-0.05,-0.39,12.630,12.642,12.723,284233.37,240418.24,250322.00,0.13
2018-01-02,12.61,12.77,12.73,12.60,313230.53,0.14,1.11,12.624,12.650,12.748,239006.61,220978.74,293300.85,0.11

In [5]:
sql00 = "drop table if exists s600000"
cursor.execute(sql00)

0

In [6]:
sql01 = """create table s600000(
               date date,
               open float,
               high float,
               low float,
               close float,
               volume float)"""
cursor.execute(sql01)

0

In [2]:
hs300 = ts.get_hs300s().code
hs300

http://www.csindex.com.cn/uploads/file/autofile/closeweight/000300closeweight.xls

0      600000
1      600008
2      600009
3      600010
4      600011
5      600015
6      600016
7      600018
8      600019
9      600021
10     600023
11     600028
12     600029
13     600030
14     600031
15     600036
16     600038
17     600048
18     600050
19     600061
20     600066
21     600068
22     600074
23     600085
24     600089
25     600100
26     600104
27     600109
28     600111
29     600115
        ...
270    002558
271    002572
272    002594
273    002601
274    002602
275    002608
276    002624
277    002673
278    002714
279    002736
280    002739
281    002797
282    002831
283    002839
284    002841
285    300003
286    300015
287    300017
288    300024
289    300027
290    300033
291    300059
292    300070
293    300072
294    300122
295    300124
296    300136
297    300144
298    300251
299    300315
Name: code, Length: 300, dtype: object

In [21]:
type(hs300.code[0])

str

In [5]:
for i in hs300:
    sql98 = "drop table if exists s"+i
    sql99 = "create table s"+i+"""(date date,open float,high float,low float,close float,volume float)"""
    cursor.execute(sql98)
    cursor.execute(sql99)

In [ ]:
for i in hs300[2:]:
    print(i)
    s_DB = ts.get_hist_data(i,start = '2018-01-01')
    if s_DB is None:
        continue
    s_DB = s_DB.iloc[:,0:5]
    s_DB.insert(0,'date',s_DB.index)
    insert_data = np.array(s_DB)
    sql02 = "insert into s"+i+"(date,open,high,low,close,volume)values(%s,%s,%s,%s,%s,%s)"
    for row in insert_data:
        cursor.execute(sql02,list(row))
    
myDB.commit()

600009
600010
600011
600015
600016
600018
600019
600021
600023
600028
600029
600030
600031
600036
600038
600048
600050
600061
600066
600068
600074
600085
600089
600100
600104
600109
600111
600115
600118
600153
600157
600170
600177
600188
600196
600208
600219
600221
600233
600271
600276
600297
600309
600332
600340
600352
600362
600369
600372
600373
600376
600383
600390
600406
600415
600436
600482
600485
600489
600498
600518
600519
600522
600535
600547
600549
600570
600583
600585
600588
600606
600637
600649
600660
600663
600674
600682
600685
600688
600690
600703
600704
600705
600739
600741
600795
600804
600816
600820
600827
600837
600871
600886
600887
600893
600895
600900
600909
600919
600926
600958
600959
600977
600999
601006
601009
601012
601018
601021
601088
601099
601111
601117
601118
601155
601163
601166
601169
601186
601198
601211
601212
601216
601225
601228
601229
601288
601318
601328
601333
601336
601375
601377
601390
601398
601555
601600
601601
601607
601608
601611
601618
601628
601633
601668
601669
601688
601718
601727
601766
601788
601800
601818
601857
601866
601872
601877
601878
601881
601888
601898
601899
601901
601919
601933
601939
601958
601966
601985
601988
601989
601991
601992
601997
601998
603160
603799
603833
603858
603993
000001
000002
000008
000060
000063
000069
000100
000157
000166
000333
000338
000402
000413
000415
000423
000425
000503
000538
000540
000559
000568
000623
000625
000627
000630
000651
000671
000686
000709
000723
000725
000728
000738
000750
000768
000776
000783
000792
000826
000839
000858
000876
000895
000898
000938
000959
000961
000963
000983
001979
002007
002008
002024
002027
002044
002065
002074
002081
002142
002146
002153
002174
002202
002230
002236
002241
002252
002292
002294
002304
002310
002352
002385
002411
002415
002424
002426
002450
002456
002460
002465
002466
002468
002470
002475

In [21]:
t = ts.get_hist_data('600009',start = '2018-01-01')
t

,open,high,close,low,volume,price_change,p_change,ma5,ma10,ma20,v_ma5,v_ma10,v_ma20,turnover
date,,,,,,,,,,,,,,
2018-03-23,48.88,50.81,50.80,48.88,97617.93,0.01,0.02,50.342,50.155,49.925,53113.31,47082.60,55864.30,0.89
2018-03-22,50.01,51.48,50.80,49.75,57330.81,0.81,1.62,50.054,50.159,49.728,41519.69,42490.37,53310.71,0.52
2018-03-21,50.33,50.85,50.02,49.60,35880.11,0.03,0.06,49.894,50.042,49.519,34408.65,40085.88,53322.39,0.33
2018-03-20,49.85,50.30,49.99,49.60,31526.65,-0.15,-0.30,49.856,49.964,49.210,34757.12,40877.30,53517.78,0.29
2018-03-19,49.02,50.29,50.10,48.80,43211.03,0.76,1.54,49.968,49.877,48.900,36890.74,42316.98,55292.90,0.40
2018-03-16,50.29,50.38,49.36,49.10,39649.86,-0.64,-1.28,49.968,49.885,48.567,41051.89,44246.21,56166.17,0.36
2018-03-15,49.48,50.15,50.00,49.41,21775.61,0.16,0.32,50.264,49.985,48.311,43461.05,47610.67,60766.60,0.20
2018-03-14,50.20,50.80,49.83,49.63,37622.47,-0.71,-1.41,50.190,49.920,48.111,45763.10,50868.04,63960.53,0.34
2018-03-13,50.12,51.40,50.55,49.85,42194.71,0.46,0.92,50.072,49.823,48.004,46997.48,53425.77,66170.18,0.39
2018-03-12,51.00,51.98,50.10,49.90,64016.82,-0.73,-1.44,49.786,49.736,47.875,47743.23,59176.52,70069.94,0.59
2018-03-09,50.00,50.88,50.84,49.41,51695.66,1.20,2.42,49.802,49.695,47.802,47440.53,64646.01,70425.97,0.47
2018-03-08,49.50,49.70,49.63,48.56,33285.86,0.41,0.83,49.706,49.297,47.699,51760.29,64131.04,71525.81,0.30
2018-03-07,49.31,49.88,49.24,49.03,43794.37,0.08,0.16,49.650,48.996,47.602,55972.97,66558.89,73531.43,0.40
2018-03-06,50.00,50.18,49.12,48.90,45923.44,-1.10,-2.19,49.574,48.455,47.484,59854.06,66158.26,73239.86,0.42
2018-03-05,50.00,50.34,50.18,48.50,62503.31,-0.17,-0.34,49.686,47.923,47.333,70609.81,68268.81,73896.95,0.57
2018-03-02,48.96,50.50,50.36,48.65,73294.46,1.03,2.09,49.588,47.248,47.108,81851.49,68086.14,73903.64,0.67
2018-03-01,48.50,49.78,49.35,48.31,54349.28,0.48,0.98,48.888,46.637,46.935,76501.79,73922.53,73361.38,0.50
2018-02-28,49.30,49.50,48.86,48.28,63199.82,-0.82,-1.65,48.342,46.301,46.798,77144.82,77053.01,73381.51,0.58
2018-02-27,49.94,50.59,49.68,48.90,99702.18,-0.01,-0.02,47.336,46.184,46.711,72462.45,78914.58,73827.82,0.91
2018-02-26,48.50,49.88,49.69,48.30,118711.71,2.83,6.04,46.160,46.013,46.579,65927.81,80963.36,76322.97,1.09
2018-02-23,46.77,47.23,46.86,46.16,46545.97,0.23,0.49,44.908,45.908,46.341,54320.78,76205.93,73344.13,0.43
2018-02-22,44.30,46.77,46.62,44.11,57564.40,2.80,6.39,44.386,46.100,46.229,71343.27,78920.59,73367.38,0.53
2018-02-14,43.41,44.00,43.83,43.22,39787.98,0.06,0.14,44.260,46.208,46.150,76961.21,80503.97,75193.98,0.36
2018-02-13,44.20,45.17,43.80,43.54,67029.01,0.37,0.85,45.032,46.513,46.228,85366.71,80321.47,76945.08,0.61
2018-02-12,43.30,43.98,43.43,43.02,60676.54,-0.79,-1.79,45.866,46.742,46.337,95998.91,79525.08,79307.50,0.55
2018-02-09,44.65,44.66,44.25,41.66,131658.44,-1.76,-3.83,46.908,46.968,46.448,98091.07,79721.15,82305.71,1.20
2018-02-08,47.20,47.90,45.99,44.80,85654.08,-1.72,-3.60,47.814,47.233,46.434,86497.90,72800.23,77807.81,0.78
2018-02-07,47.99,48.10,47.69,46.25,81815.47,-0.30,-0.62,48.156,47.294,46.306,84046.73,69710.00,75605.06,0.75
2018-02-06,47.23,48.00,47.97,46.15,120190.02,-0.63,-1.30,47.994,47.237,46.110,75276.24,68741.07,73923.59,1.10
2018-02-05,48.30,49.20,48.64,47.58,71137.35,-0.14,-0.29,47.618,47.145,45.899,63051.25,71682.58,72019.95,0.65
2018-02-02,47.70,48.98,48.78,46.80,73692.57,1.10,2.31,47.028,46.774,45.618,61351.23,70482.34,73537.01,0.67
2018-02-01,46.88,47.73,47.70,46.42,73398.23,0.81,1.73,46.652,46.358,45.385,59102.56,67814.18,72508.22,0.67
2018-01-31,45.86,46.90,46.88,45.67,37963.02,0.75,1.63,46.432,46.091,45.206,55373.28,69883.99,71786.59,0.35
2018-01-30,45.45,46.40,46.09,45.43,59065.08,0.41,0.90,46.480,45.943,45.070,62205.90,73568.68,74487.12,0.54
2018-01-29,47.13,47.13,45.69,45.43,62637.27,-1.19,-2.54,46.672,45.932,44.986,80313.90,79089.91,74519.77,0.57
2018-01-26,46.66,47.48,46.90,46.57,62449.18,0.23,0.49,46.520,45.928,44.952,79613.44,84890.27,74058.38,0.57
2018-01-25,46.66,47.17,46.60,46.21,54751.83,-0.49,-1.04,46.064,45.634,44.811,76525.80,82815.39,72685.37,0.50
2018-01-24,46.83,47.21,47.12,46.35,72126.14,0.10,0.21,45.750,45.318,44.686,84394.70,81500.12,72608.92,0.66
2018-01-23,45.35,47.47,47.05,45.12,149605.08,2.14,4.76,45.406,44.984,44.580,84931.45,79106.11,71824.66,1.37
2018-01-22,44.61,45.16,44.93,44.26,59134.99,0.32,0.72,45.192,44.652,44.444,77865.93,72357.32,66079.04,0.54
2018-01-19,44.99,45.30,44.62,44.46,47010.98,-0.38,-0.84,45.336,44.461,44.410,90167.09,76591.68,65813.45,0.43
2018-01-18,45.46,46.05,45.03,44.70,94096.33,-0.35,-0.77,45.204,44.411,44.445,89104.98,77202.25,66659.70,0.86
2018-01-17,46.42,46.80,45.40,45.11,74809.89,-0.56,-1.22,44.886,44.320,44.432,78605.54,73689.19,64231.97,0.68
2018-01-16,46.00,46.59,45.98,45.51,114277.46,0.33,0.72,44.562,44.196,44.381,73280.78,75405.57,62864.57,1.05
2018-01-15,44.38,46.44,45.65,44.00,120640.78,1.71,3.89,44.112,44.040,44.280,66848.71,69949.62,59259.97,1.10
2018-01-12,43.52,44.03,43.96,43.20,41700.45,0.52,1.20,43.586,43.976,44.179,63016.27,63226.50,55392.32,0.38
2018-01-11,43.80,44.19,43.44,43.16,41599.13,-0.36,-0.82,43.618,43.988,44.155,65299.52,62555.35,55837.10,0.38
2018-01-10,44.04,44.18,43.78,43.50,48186.06,0.02,0.05,43.754,44.054,44.182,68772.85,63717.71,57714.69,0.44
2018-01-09,43.05,43.82,43.73,43.03,82117.14,0.70,1.63,43.830,44.175,44.119,77530.36,64543.20,58146.08,0.75
2018-01-08,44.15,44.35,43.02,42.73,101478.58,-1.13,-2.56,43.968,44.235,44.094,73050.52,59800.76,56912.06,0.93
2018-01-05,44.32,44.55,44.12,44.01,53116.71,0.02,0.04,44.366,44.359,44.042,63436.72,55035.23,54815.79,0.49
2018-01-04,43.98,44.43,44.12,43.58,58965.74,0.07,0.16,44.358,44.478,43.935,59811.17,56117.15,55523.63,0.54
2018-01-03,44.44,44.93,44.16,43.73,91973.65,-0.24,-0.54,44.354,44.543,43.830,58662.57,54774.74,57375.19,0.84
2018-01-02,45.00,45.33,44.42,44.13,59717.92,-0.59,-1.31,44.520,44.565,43.793,51556.05,50323.58,56525.25,0.55

In [27]:
if t is None:
    print('0')

In [ ]:
#0-2

In [24]:
myDB.rollback()

In [7]:
nDB = s_DB.iloc[:,0:5]

In [8]:
nDB.insert(0,'date',s_DB.index)

In [9]:
insert_data = np.array(nDB)

In [11]:
sql02 = "insert into s600000(date,open,high,low,close,volume)values('2018-03-01', 12.4, 12.5, 12.46, 12.38, 344910.31)"
cursor.execute(sql02)

1

In [12]:
sql02 = "insert into s600000(date,open,high,low,close,volume)values(%s,%s,%s,%s,%s,%s)"
for row in insert_data:
    cursor.execute(sql02,list(row))
myDB.commit()

In [35]:
sql03 = """select * from s600008"""
cursor.execute(sql03)
table = cursor.fetchall()
table

((datetime.date(2018, 3, 23), 5.02, 5.13, 5.12, 4.8, 1231610.0),
 (datetime.date(2018, 3, 22), 5.06, 5.13, 5.12, 5.02, 334816.0),
 (datetime.date(2018, 3, 21), 5.1, 5.19, 5.12, 5.05, 338774.0),
 (datetime.date(2018, 3, 20), 5.08, 5.15, 5.1, 5.0, 389690.0),
 (datetime.date(2018, 3, 19), 5.1, 5.16, 5.1, 5.06, 267372.0),
 (datetime.date(2018, 3, 16), 5.1, 5.13, 5.06, 5.05, 243010.0),
 (datetime.date(2018, 3, 15), 5.11, 5.25, 5.13, 5.08, 366197.0),
 (datetime.date(2018, 3, 14), 5.17, 5.2, 5.12, 5.11, 309804.0),
 (datetime.date(2018, 3, 13), 5.22, 5.24, 5.16, 5.16, 325454.0),
 (datetime.date(2018, 3, 12), 5.2, 5.28, 5.25, 5.14, 630092.0),
 (datetime.date(2018, 3, 9), 5.28, 5.38, 5.24, 5.17, 1022050.0),
 (datetime.date(2018, 3, 8), 4.97, 5.43, 5.3, 4.94, 1365260.0),
 (datetime.date(2018, 3, 7), 5.03, 5.05, 4.98, 4.97, 315618.0),
 (datetime.date(2018, 3, 6), 4.99, 5.09, 5.05, 4.97, 448739.0),
 (datetime.date(2018, 3, 5), 5.0, 5.02, 4.98, 4.95, 261598.0),
 (datetime.date(2018, 3, 2), 4.94, 5.04, 5.0, 4.92, 407791.0),
 (datetime.date(2018, 3, 1), 4.92, 5.0, 4.96, 4.92, 305833.0),
 (datetime.date(2018, 2, 28), 4.9, 5.04, 4.97, 4.89, 390531.0),
 (datetime.date(2018, 2, 27), 5.04, 5.04, 4.97, 4.94, 432033.0),
 (datetime.date(2018, 2, 26), 5.0, 5.05, 5.03, 4.88, 589593.0),
 (datetime.date(2018, 2, 23), 5.0, 5.14, 4.93, 4.9, 823272.0),
 (datetime.date(2018, 2, 22), 4.7, 5.01, 4.87, 4.64, 591155.0),
 (datetime.date(2018, 2, 14), 4.6, 4.65, 4.63, 4.58, 198472.0),
 (datetime.date(2018, 2, 13), 4.55, 4.74, 4.6, 4.53, 294883.0),
 (datetime.date(2018, 2, 12), 4.47, 4.53, 4.5, 4.45, 172167.0),
 (datetime.date(2018, 2, 9), 4.58, 4.64, 4.44, 4.29, 372479.0),
 (datetime.date(2018, 2, 8), 4.64, 4.72, 4.69, 4.6, 212955.0),
 (datetime.date(2018, 2, 7), 4.72, 4.75, 4.63, 4.54, 323449.0),
 (datetime.date(2018, 2, 6), 4.95, 4.95, 4.63, 4.6, 506128.0),
 (datetime.date(2018, 2, 5), 5.06, 5.06, 5.02, 4.97, 281166.0),
 (datetime.date(2018, 2, 2), 5.0, 5.06, 5.05, 4.88, 289541.0),
 (datetime.date(2018, 2, 1), 5.2, 5.22, 5.0, 4.99, 486769.0),
 (datetime.date(2018, 1, 31), 5.27, 5.28, 5.18, 5.16, 348058.0),
 (datetime.date(2018, 1, 30), 5.3, 5.34, 5.27, 5.25, 257664.0),
 (datetime.date(2018, 1, 29), 5.45, 5.48, 5.31, 5.29, 454444.0),
 (datetime.date(2018, 1, 26), 5.51, 5.56, 5.45, 5.43, 391577.0),
 (datetime.date(2018, 1, 25), 5.47, 5.58, 5.5, 5.44, 597942.0),
 (datetime.date(2018, 1, 24), 5.46, 5.55, 5.49, 5.39, 626501.0),
 (datetime.date(2018, 1, 23), 5.47, 5.51, 5.48, 5.43, 432676.0),
 (datetime.date(2018, 1, 22), 5.49, 5.53, 5.49, 5.4, 457080.0),
 (datetime.date(2018, 1, 19), 5.41, 5.51, 5.46, 5.38, 465060.0),
 (datetime.date(2018, 1, 18), 5.43, 5.48, 5.41, 5.4, 319673.0),
 (datetime.date(2018, 1, 17), 5.39, 5.48, 5.45, 5.28, 645755.0),
 (datetime.date(2018, 1, 16), 5.28, 5.38, 5.37, 5.27, 351332.0),
 (datetime.date(2018, 1, 15), 5.49, 5.5, 5.32, 5.3, 468777.0),
 (datetime.date(2018, 1, 12), 5.44, 5.55, 5.47, 5.43, 494303.0),
 (datetime.date(2018, 1, 11), 5.48, 5.48, 5.47, 5.4, 439029.0),
 (datetime.date(2018, 1, 10), 5.56, 5.58, 5.51, 5.47, 541616.0),
 (datetime.date(2018, 1, 9), 5.67, 5.73, 5.59, 5.54, 789940.0),
 (datetime.date(2018, 1, 8), 5.64, 5.72, 5.66, 5.63, 789920.0),
 (datetime.date(2018, 1, 5), 5.66, 5.79, 5.73, 5.61, 1545150.0),
 (datetime.date(2018, 1, 4), 6.01, 6.07, 5.82, 5.76, 2914750.0),
 (datetime.date(2018, 1, 3), 5.3, 5.72, 5.72, 5.29, 1425840.0),
 (datetime.date(2018, 1, 2), 5.15, 5.22, 5.2, 5.13, 351744.0))